### ISSUE TITLE
TypeError: self._pool.delete is not a function

### ISSUE THREAD

**Issue by chrisabrams** [mbroadst/rethunk#3]
node_modules/rethunk/lib/pool.js:258
          self._pool.delete(i);
                           ^

TypeError: self._pool.delete is not a function
    at Connection.<anonymous> (node_modules/rethunk/lib/pool.js:258:28)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (node_modules/rethunk/lib/connection.js:98:10)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by chrisabrams** [comment]
@mbroadst I seem to get this error a lot. Any idea if this is a library issue or a symptom of an app issue?

**Comment by chrisabrams** [comment]
I'm able to confirm this in indeed an issue that arises from an app that tries to run operations against a database that does not exist.
